### PR TITLE
Test Warrior.Map.Builder

### PR DESCRIPTION
**Pull request by sparksp**
Outstanding (skipped) tests:

- Warrior.Map.Builder.withNpc https://github.com/Skinney/elm-warrior/pull/12
  - [x] What should happen when a NPC is placed on top of another NPC?
  - [x] What should happen when a NPC is placed out of bounds?
- Warrior.Map.Builder.withWalledArea https://github.com/Skinney/elm-warrior/pull/3
  - [x] Prevent out of bound wall areas.

### CODE REVIEW

**Comment by sparksp** [comment]
Hey @Skinney - it would be great to get your thoughts on the behaviour of `Warrior.Map.Builder.withNpc`...
- What should happen when a NPC is placed on top of another NPC?
- What should happen when a NPC is placed out of bounds?

**Comment by robinheghan** [comment]
Good questions!

1. What should happen when a NPC is placed on top of another NPC? It makes sense to me that the last NPC placed "wins".

2. What should happen when a NPC is placed out of bounds? It makes sense to me here that the NPC (or item, for that matter) is ignored. Having to deal with `Result` or similar in this case would make it harder to define new maps, and I think silently ignoring the request is the best overall trade off.

**Comment by sparksp** [comment]
So in both of these cases we would not expect the rejected NPC (either the one being replaced or one placed out of bounds) to be in the resulting NPC list?

This happens when an Item is placed on top of another Item; but out of bound items are still added.

**Comment by robinheghan** [comment]
Yes. Replaced or out-of-bound NPCs and items should not be in the resulting NPC/Item list.

**Pull request merged**
